services:
  # Database 1: PostgreSQL
  postgres:
    image: quay.io/debezium/postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=password_postgres
      - POSTGRES_DB=inventory_db_postgres

  # Database 2: MySQL
  mysql:
    image: mysql:8.2
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password_mysql_root
      - MYSQL_DATABASE=inventory_db_mysql
    # Cấu hình Binlog trực tiếp qua command để Debezium đọc được
    command: 
      - --gtid_mode=ON
      - --enforce_gtid_consistency=ON
      - --binlog_format=ROW
      - --server-id=184054
      - --log-bin=mysql-bin

  kafka:
    image: quay.io/debezium/kafka:2.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - CLUSTER_ID=5Y2s9BE9TTe967ue4E7v7g
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_SKIP_KRAFT_STORAGE_CHECK=true

  connect:
    image: quay.io/debezium/connect:2.5
    container_name: connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      # Tắt Schemas để JSON gọn nhẹ, dễ đọc
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=debezium
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://connect:8083
